services:
  permitta:
    url: http://host.docker.internal:8000/
    response_header_timeout_seconds: 5
    credentials:
      bearer:
        token: "bGFza2RqZmxha3NkamZsa2Fqc2Rsa2ZqYWtsc2RqZmtramRmYWxkc2tm"

bundles:
  trino:
    service: django
    resource: bundles/django/bundle.tar.gz
    persist: true
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120
#    signing:
#      keyid: global_key
#      scope: write

persistence_directory: /policy/persistence
