version: '2'
services:
#  opa:
#    image: openpolicyagent/opa:latest
#    ports:
#      - 8181:8181
#    command:
#      - "run"
#      - "--server"
#      - "--log-level=debug"
#      - "-c"
#      - "/policy/config.yaml"
#    volumes:
#      - ./policy:/policy
  keycloak:
    image: keycloak/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - "start-dev"

  lldap:
    image: lldap/lldap:stable
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      - "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      # Alternatively, you can mount a local folder
     - ./instance/lldap:/data
     - ./lldap/bootstrap:/bootstrap
    environment:
      - UID=1000
      - GID=1000
      - TZ=Australia/Melbourne
      - LLDAP_JWT_SECRET=jhgfdfjkhgsdfghlushdvndkfjnsd
      - LLDAP_KEY_SEED=ioajerjgosdfvnsdufghbsiudhgjfdvn
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com

      # envs required for lldap
      - LLDAP_LDAP_USER_EMAIL=admin@example.com
      - LLDAP_LDAP_USER_PASS=changeme

      # envs required for bootstrap.sh
      - LLDAP_URL=http://localhost:17170
      - LLDAP_ADMIN_USERNAME=admin
      - LLDAP_ADMIN_PASSWORD=changeme # same as LLDAP_LDAP_USER_PASS
      - USER_CONFIGS_DIR=/bootstrap/user-configs
      - GROUP_CONFIGS_DIR=/bootstrap/group-configs
      - DO_CLEANUP=true

#