version: '2'
services:
#  opa:
#    image: openpolicyagent/opa:latest
#    ports:
#      - 8181:8181
#    command:
#      - "run"
#      - "--server"
#      - "--log-level=debug"
#      - "-c"
#      - "/policy/config.yaml"
#    volumes:
#      - ./policy:/policy
  keycloak:
    image: keycloak/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - "start-dev"