site_name: Permitta
theme:
  name: material
  features:
    - navigation.expand
    - navigation.path
repo_url: https://github.com/permitta/permitta
dev_addr: localhost:8001

# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

nav:
  - Home: index.md
  - Developer Setup: developer_setup.md
  - Policies:
    - Policy Management: policies/listing.md
    - Visual Builder: policies/builder.md
    - DSL Editor: policies/dsl_editor.md
  - Security:
      - Auth: security/auth.md
  - Configuration:
      - Configuration File: config/configuration.md
      - Logging: config/properties_logging.md
      - OIDC: config/properties_oidc.md
      - OPA Authorisation: config/properties_opa_authz.md
      - LDAP Client: config/properties_ldap_client.md
