database.connection_string: "sqlite:///:memory:"
common.db_connection_string: "sqlite:///:memory:"
common.super_secret: "https:/domain?username=$SUPER_SECRET_VALUE"
connector.json_file.principals.file_path: "config/principals.json"
oidc_auth_provider.issuer: "http://example.com/realms/permitta"
oidc_auth_provider.client_id: "permitta-client"
oidc_auth_provider.client_secret: "super-secret"
